import type { Difficulty, DifficultyConfig } from '../types/tcg'

export const DIFFICULTIES: Record<Difficulty, DifficultyConfig> = {
  easy: {
    id: 'easy',
    label: 'Easy',
    packSize: 3,
    rounds: 8,
    previewSeconds: 3,
    timeLimit: 75,
    winScore: 4,
    pointsPerCorrect: 1,
    rewardCards: 3,
    questionTypes: ['name', 'supertype', 'rarity'],
  },
  medium: {
    id: 'medium',
    label: 'Medium',
    packSize: 4,
    rounds: 8,
    previewSeconds: 2,
    timeLimit: 70,
    winScore: 4,
    pointsPerCorrect: 1,
    rewardCards: 5,
    questionTypes: ['name', 'rarity', 'supertype', 'number', 'pokemonType'],
  },
  hard: {
    id: 'hard',
    label: 'Hard',
    packSize: 6,
    rounds: 8,
    previewSeconds: 2,
    timeLimit: 65,
    winScore: 4,
    pointsPerCorrect: 1,
    rewardCards: 7,
    questionTypes: [
      'name',
      'rarity',
      'supertype',
      'number',
      'artist',
      'pokemonType',
      'hp',
    ],
  },
  extreme: {
    id: 'extreme',
    label: 'Extreme',
    packSize: 8,
    rounds: 10,
    previewSeconds: 1,
    timeLimit: 55,
    winScore: 4,
    pointsPerCorrect: 1,
    rewardCards: 15,
    questionTypes: [
      'name',
      'rarity',
      'supertype',
      'number',
      'artist',
      'pokemonType',
      'hp',
    ],
  },
}

export const difficultyOrder: Difficulty[] = [
  'easy',
  'medium',
  'hard',
  'extreme',
]
